// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Q2baranov
NumericVector Q2baranov(NumericVector e, List inputs, IntegerVector idx);
RcppExport SEXP _FLBEIA_Q2baranov(SEXP eSEXP, SEXP inputsSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type e(eSEXP);
    Rcpp::traits::input_parameter< List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(Q2baranov(e, inputs, idx));
    return rcpp_result_gen;
END_RCPP
}
// update_catch_effort_FLFleets
S4 update_catch_effort_FLFleets(NumericMatrix effort, S4 fleets, List inputs, int year);
RcppExport SEXP _FLBEIA_update_catch_effort_FLFleets(SEXP effortSEXP, SEXP fleetsSEXP, SEXP inputsSEXP, SEXP yearSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type effort(effortSEXP);
    Rcpp::traits::input_parameter< S4 >::type fleets(fleetsSEXP);
    Rcpp::traits::input_parameter< List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< int >::type year(yearSEXP);
    rcpp_result_gen = Rcpp::wrap(update_catch_effort_FLFleets(effort, fleets, inputs, year));
    return rcpp_result_gen;
END_RCPP
}
// fill_flcatches
S4 fill_flcatches(S4 fl, S4 cobj, CharacterVector st, int mt_idx);
RcppExport SEXP _FLBEIA_fill_flcatches(SEXP flSEXP, SEXP cobjSEXP, SEXP stSEXP, SEXP mt_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type fl(flSEXP);
    Rcpp::traits::input_parameter< S4 >::type cobj(cobjSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type st(stSEXP);
    Rcpp::traits::input_parameter< int >::type mt_idx(mt_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(fill_flcatches(fl, cobj, st, mt_idx));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FLBEIA_Q2baranov", (DL_FUNC) &_FLBEIA_Q2baranov, 3},
    {"_FLBEIA_update_catch_effort_FLFleets", (DL_FUNC) &_FLBEIA_update_catch_effort_FLFleets, 4},
    {"_FLBEIA_fill_flcatches", (DL_FUNC) &_FLBEIA_fill_flcatches, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_FLBEIA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
