# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fill_flcatches <- function(fl, cobj, st, mt_idx) {
    .Call(`_FLBEIA_fill_flcatches`, fl, cobj, st, mt_idx)
}

