# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Q2baranov <- function(e, inputs, idx) {
    .Call(`_FLBEIA_Q2baranov`, e, inputs, idx)
}

update_catch_effort_FLFleets <- function(effort, fleets, inputs, year) {
    .Call(`_FLBEIA_update_catch_effort_FLFleets`, effort, fleets, inputs, year)
}

fill_flcatches <- function(fl, cobj, st, mt_idx) {
    .Call(`_FLBEIA_fill_flcatches`, fl, cobj, st, mt_idx)
}

